### ISSUE TITLE
 bower install kendo-ui-core command fails

### ISSUE THREAD

**Issue by frontenddeveloping** [telerik/kendo-ui-core#1383]
Use cygwin console:

>
$ bower install kendo-ui-core
bower kendo-ui-core#*       not-cached git://github.com/kendo-labs/bower-kendo-ui.git#*
bower kendo-ui-core#*          resolve git://github.com/kendo-labs/bower-kendo-ui.git#*
bower kendo-ui-core#*           ENOENT spawn git ENOENT

>Stack trace:
Error: spawn git ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

>Console trace:
Error
    at StandardRenderer.error (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\bin\bower:116:30)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.2
Node version: 5.4.1
OS: Windows_NT 10.0.10586 x64

**Comment by frontenddeveloping** [comment]
My local problem - try to install to deleted folder
