### ISSUE TITLE
Importing Kendo UI in an Angular Project throws an error in kendo.colorpicker.js

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6735]
### Bug report

Using Kendo UI in an Angular Project throws a "Cannot read properties of undefined (reading 'options')" error in kendo.colorpicker.js.

**Regression with version 2022.1.119**

### Reproduction of the problem

1. Open the attached project.
2. Run npm install
3. Run npm run start

### Current behavior
An error is thrown on line 279 in kendo.colorpicker.js - this is undefined.

### Expected/desired behavior
No error should be thrown

### Environment

* **Kendo UI version:** 2022.1.119
* **Browser:** [all] 

[issue-kendo-ui.zip](https://github.com/telerik/kendo-ui-core/files/8096889/issue-kendo-ui.zip)

**Comment by jvalkeejarvi** [comment]
I patched this colorpicker issue manually, but faced a similar issue with some other components.
For example grids numeric filter does not work because of following error:
```
TypeError: Cannot read properties of undefined (reading 'options')
    at buttonHtml (kendo.numerictextbox.js:1044:188)
    at init._arrows (kendo.numerictextbox.js:464:1)
    at new init (kendo.numerictextbox.js:174:1)
    at Object.kendo.initWidget (kendo.core.js:3302:1)
    at bindingTargetForRole (kendo.binder.js:1920:1)
    at bindElement (kendo.binder.js:1992:1)
    at bindElement (kendo.binder.js:2054:1)
    at Object.bind (kendo.binder.js:2071:1)
    at init.refresh (kendo.filtermenu.js:713:1)
    at init._init (kendo.filtermenu.js:552:1)
```

Will all similar issues be fixed when this fix is released?
