### ISSUE TITLE
Filtering a Grid column, bound to a complex object, throws a JavaScript error

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#7183]
### Bug report

Filtering a column bound to a complex object throws a JavaScript error. 
This is a regression introduced with v 2023.1.117
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at x (kendo.all.js:313050:21)
    at init._createForm (kendo.all.js:313050:21)
    at init._init (kendo.all.js:313050:21)
    at init._click (kendo.all.js:313050:21)
    at HTMLAnchorElement.dispatch (jquery.min.js:3:12445)
    at r.handle (jquery.min.js:3:9174)
```

### Reproduction of the problem
1. Run this [REPL](https://netcorerepl.telerik.com/mnOPwhaZ49BWEXAb16) or this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/oyoYiSIc)
2. Click on the filter icon of the Category column

### Current behavior
JavaScript error is thrown and the filter menu is not generated.

### Expected/desired behavior
Filtering should work as expected.

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all]

**Comment by lsiepel** [comment]
Hope this get fixed soon as it prevents us from further upgrading.
