### ISSUE TITLE
cant't add new row : Uncaught DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 1

### ISSUE THREAD

**Issue by jpprsaran** [telerik/kendo-ui-core#7221]
cant't add new row : Uncaught DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 1

After copying the text (Text is framed using the text editor) click enter key. Enter key is not working and the Error is: Uncaught DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 1

Uncaught DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 1.
    at init.toRangePoint (scripts/vendor/kendo/kendo.all.min.js:68:30405)
    at init.toRange (scripts/vendor/kendo/kendo.all.min.js:68:30474)
    at init.getRange (/scripts/vendor/kendo/kendo.all.min.js:69:9677)
    at init.exec (/scripts/vendor/kendo/kendo.all.min.js:71:19138)
    at init.execCommand (/scripts/vendor/kendo/kendo.all.min.js:67:22412)
    at init.exec (/scripts/vendor/kendo/kendo.all.min.js:67:22237)
    at HTMLDivElement.keydown (/scripts/vendor/kendo/kendo.all.min.js:67:14131)
    at HTMLDivElement.dispatch (/scripts/vendor/jquery-3.4.1.js:5237:27)
    at elemData.handle (/scripts/vendor/jquery-3.4.1.js:5044:28)
toRangePoint @ kendo.all.js:80600
toRange @ kendo.all.js:80602
getRange @ kendo.all.js:81262
exec @ kendo.all.js:85318
execCommand @ kendo.all.js:78086
exec @ kendo.all.js:78072
keydown @ kendo.all.js:77582
dispatch @ jquery-3.4.1.js:5237
elemData.handle @ jquery-3.4.1.js:5044

**Comment by Dimitar-Goshev** [comment]
@jpprsaran Please provide a reproduction URL or Dojo snippet showing the setup used and provide steps to reproduce the error with it.

**Comment by jpprsaran** [comment]
@Dimitar-Goshev - please refer to the link for more details about the issue: https://github.com/telerik/kendo-ui-core/issues/5975

Video link: https://www.screencast.com/t/D4ca3VsbDiX

**Comment by eyupyusein** [comment]
Closing as duplicate of:
https://github.com/telerik/kendo-ui-core/issues/5975
